[lint]
ignore = [
  "E701", # multiple statements using colon (single-line if's etc.)
  "E702", # multiple statements using semicolon
  "E402", # import not at the top
  "E741", # typographically easy to mix variables like l
  ]

#allowed-confusables = ["l"]
